export const LOAD_TABLES_SUCCESS = 'LOAD_TABLES_SUCCESS'
export const LOAD_TICKETS_SUCCESS = 'LOAD_TICKETS_SUCCESS'
export const LOAD_CLIENTS_SUCCESS = 'LOAD_CLIENTS_SUCCESS'
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS'

export const LOAD_TABLES_ERROR = 'LOAD_TABLES_ERROR'
export const LOAD_TICKETS_ERROR = 'LOAD_TICKETS_ERROR'
export const LOAD_CLIENTS_ERROR = 'LOAD_CLIENTS_ERROR'
export const LOAD_PRODUCTS_ERROR = 'LOAD_PRODUCTS_ERROR'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOAD_CATEGORIES_ERROR = 'LOAD_CATEGORIES_ERROR'
// Ticket
export const LOAD_TICKET_SUCCESS = 'LOAD_TICKET_SUCCESS'
export const LOAD_TICKET_ERROR = 'LOAD_TICKET_ERROR'
// Payments
export const LOAD_TICKET_PAYMENTS_SUCCESS = 'LOAD_TICKET_PAYMENTS_SUCCESS'
export const LOAD_TICKET_PAYMENTS_ERROR = 'LOAD_TICKET_PAYMENTS_ERROR'
export const ADD_TICKET_PAYMENT_SUCCESS = 'ADD_TICKET_PAYMENT_SUCCESS'
export const REMOVE_TICKET_PAYMENT_SUCCESS = 'REMOVE_TICKET_PAYMENT_SUCCESS'
// Entries
export const LOAD_TICKET_ENTRIES_SUCCESS = 'LOAD_TICKET_ENTRIES_SUCCESS'
export const LOAD_TICKET_ENTRIES_ERROR = 'LOAD_TICKET_ENTRIES_ERROR'
export const ADD_TICKET_ENTRY_SUCCESS = 'ADD_TICKET_ENTRY_SUCCESS'
export const REMOVE_TICKET_ENTRY_SUCCESS = 'REMOVE_TICKET_ENTRY_SUCCESS'
export const UPDATE_ENTRY_SUCCESS = 'UPDATE_ENTRY_SUCCESS'
// Tables
export const ADD_TABLE_SUCCESS = 'ADD_TABLE_SUCCESS'
export const OPEN_TABLE_SUCCESS = 'OPEN_TABLE_SUCCESS'
// Clients
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS'
