export const LOAD_TABLES_SUCCESS = 'LOAD_TABLES_SUCCESS'
export const LOAD_TICKETS_SUCCESS = 'LOAD_TICKETS_SUCCESS'
export const LOAD_CLIENTS_SUCCESS = 'LOAD_CLIENTS_SUCCESS'

export const LOAD_TABLES_ERROR = 'LOAD_TABLES_ERROR'
export const LOAD_TICKETS_ERROR = 'LOAD_TICKETS_ERROR'
export const LOAD_CLIENTS_ERROR = 'LOAD_CLIENTS_ERROR'
